-- https://school.programmers.co.kr/learn/courses/30/lessons/131124

-- mysql
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW A LEFT JOIN MEMBER_PROFILE B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(MEMBER_ID) = (
        SELECT MAX(CNT)
        FROM (
        SELECT COUNT(MEMBER_ID) CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ) CNT_TBL
    )    
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;

-- oracle
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW A LEFT JOIN MEMBER_PROFILE B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(MEMBER_ID) = (
        SELECT MAX(CNT)
        FROM (
        SELECT COUNT(MEMBER_ID) CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ) CNT_TBL
    )    
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;