-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

-- mysql
SELECT YEAR(SALES_DATE) YEAR, 
       MONTH(SALES_DATE) MONTH, 
       COUNT(DISTINCT A.USER_ID) PURCHASED_USERS,
       ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(JOINED) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM ONLINE_SALE A LEFT JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;

-- oracle
SELECT TO_NUMBER(TO_CHAR(SALES_DATE, 'YYYY')) YEAR, 
       TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH, 
       COUNT(DISTINCT A.USER_ID) PURCHASED_USERS,
       ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(JOINED) FROM USER_INFO WHERE TO_NUMBER(TO_CHAR(JOINED, 'YYYY')) = 2021), 1) PUCHASED_RATIO
FROM ONLINE_SALE A LEFT JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
WHERE TO_NUMBER(TO_CHAR(JOINED, 'YYYY')) = 2021
GROUP BY TO_NUMBER(TO_CHAR(SALES_DATE, 'YYYY')), TO_NUMBER(TO_CHAR(SALES_DATE, 'MM'))
ORDER BY YEAR, MONTH;