-- https://school.programmers.co.kr/learn/courses/30/lessons/131533

-- mysql
SELECT PRODUCT_CODE, IFNULL(SUM(PRICE * SALES_AMOUNT), 0) SALES
FROM PRODUCT A LEFT JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;

-- oracle
SELECT PRODUCT_CODE, NVL(SUM(PRICE * SALES_AMOUNT), 0) SALES
FROM PRODUCT A LEFT JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;