-- https://school.programmers.co.kr/learn/courses/30/lessons/133027

-- mysql
SELECT A.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL1
    FROM FIRST_HALF GROUP BY FLAVOR
) A INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL2
    FROM JULY GROUP BY FLAVOR
) B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY SUM(TOTAL1 + TOTAL2) DESC
LIMIT 3;

-- oracle
SELECT *
FROM (
    SELECT A.FLAVOR
    FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL1
        FROM FIRST_HALF GROUP BY FLAVOR
    ) A INNER JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL2
        FROM JULY GROUP BY FLAVOR
    ) B
    ON A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR
    ORDER BY SUM(TOTAL1 + TOTAL2) DESC
)
WHERE ROWNUM <= 3;

