-- https://school.programmers.co.kr/learn/courses/30/lessons/157341?language=mysql

-- mysql
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC;


-- oracle
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) AND TO_NUMBER(TO_CHAR(START_DATE, 'MM')) = 10
ORDER BY CAR_ID DESC;