-- https://school.programmers.co.kr/learn/courses/30/lessons/131529?language=mysql

-- mysql
SELECT LEFT(PRODUCT_CODE, 2) CATEGORY, COUNT(*) PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY;

-- oracle
SELECT SUBSTR(PRODUCT_CODE, 1, 2) CATEGORY, COUNT(*) PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE, 1, 2)
ORDER BY SUBSTR(PRODUCT_CODE, 1, 2);