-- https://school.programmers.co.kr/learn/courses/30/lessons/151141

-- mysql
SELECT A.HISTORY_ID, 
       ROUND(CASE WHEN A.DURATION_TYPE IS NULL THEN  PURE_FEE
       ELSE PURE_FEE * (100-DISCOUNT_RATE)/100 END, 0) FEE
FROM (
    SELECT HISTORY_ID, (DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)) PURE_FEE,
           CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
           WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
           WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상' END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A INNER JOIN CAR_RENTAL_COMPANY_CAR B
    ON A.CAR_ID = B.CAR_ID
    WHERE CAR_TYPE = '트럭'
) A LEFT JOIN (
    SELECT *, REGEXP_REPLACE(DURATION_TYPE, '[가-힣]', '') DURATION_NUMBER
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) B
ON A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, A.HISTORY_ID DESC;




-- oracle
SELECT HISTORY_ID,
       ROUND(CASE WHEN A.DURATION_TYPE IS NULL THEN  PURE_FEE
       ELSE PURE_FEE * (100-DISCOUNT_RATE)/100 END, 0) FEE
FROM (
    SELECT HISTORY_ID, (DAILY_FEE * (END_DATE - START_DATE + 1)) PURE_FEE,
           CASE WHEN (END_DATE - START_DATE) + 1 >= 90 THEN '90일 이상'
           WHEN (END_DATE - START_DATE) + 1 >= 30 THEN '30일 이상'
           WHEN (END_DATE - START_DATE) + 1 >= 7 THEN '7일 이상' END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A INNER JOIN CAR_RENTAL_COMPANY_CAR B
    ON A.CAR_ID = B.CAR_ID
    WHERE CAR_TYPE = '트럭'
) A LEFT JOIN (
    SELECT PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE,
           REGEXP_REPLACE(DURATION_TYPE, '[가-힣]', '') DURATION_NUMBER
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) B
ON A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;