-- https://school.programmers.co.kr/learn/courses/30/lessons/157342#qna

-- mysql
SELECT CAR_ID, ROUND((SUM(DATEDIFF(END_DATE, START_DATE) + 1) / COUNT(CAR_ID)), 1) AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

-- oracle
SELECT CAR_ID, ROUND((SUM(END_DATE - START_DATE + 1) / COUNT(CAR_ID)), 1) AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND((SUM(END_DATE - START_DATE + 1) / COUNT(CAR_ID)), 1) >= 7
ORDER BY ROUND((SUM(END_DATE - START_DATE + 1) / COUNT(CAR_ID)), 1) DESC, CAR_ID DESC;