-- https://school.programmers.co.kr/learn/courses/30/lessons/151138#qna

-- mysql
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') END_DATE, CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '장기 대여' ELSE '단기 대여' END RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) = 9 AND YEAR(START_DATE) = 2022
ORDER BY HISTORY_ID DESC;

-- oracle
SELECT HISTORY_ID, CAR_ID, TO_CHAR(START_DATE, 'YYYY-MM-DD') START_DATE, 
       TO_CHAR(END_DATE, 'YYYY-MM-DD') END_DATE, 
       CASE WHEN TO_NUMBER(TO_CHAR(END_DATE - START_DATE + 1)) >= 30 THEN '장기 대여' ELSE '단기 대여' END RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_NUMBER(TO_CHAR(START_DATE, 'MM')) = 9 AND TO_NUMBER(TO_CHAR(START_DATE, 'YYYY')) = 2022
ORDER BY HISTORY_ID DESC;