-- https://school.programmers.co.kr/learn/courses/30/lessons/132204

-- mysql
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A INNER JOIN PATIENT B ON A.PT_NO = B.PT_NO
     INNER JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD;



-- oracle
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A INNER JOIN PATIENT B ON A.PT_NO = B.PT_NO
     INNER JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE TO_CHAR(APNT_YMD, 'YYYY-MM-DD') = '2022-04-13' AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD;