-- https://school.programmers.co.kr/learn/courses/30/lessons/151137?language=mysql

-- mysql
SELECT CAR_TYPE, COUNT(OPTIONS) CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE  REGEXP_LIKE(OPTIONS, '통풍시트|열선시트|가죽시트')
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE;

-- oracle
SELECT CAR_TYPE, COUNT(OPTIONS) CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE  REGEXP_LIKE(OPTIONS, '통풍시트|열선시트|가죽시트')
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE;