-- https://school.programmers.co.kr/learn/courses/30/lessons/144856?language=mysql

-- mysql
SELECT AB.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
FROM (SELECT *
    FROM BOOK NATURAL JOIN BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') AB 
    INNER JOIN AUTHOR C
ON AB.AUTHOR_ID = C.AUTHOR_ID
GROUP BY AB.AUTHOR_ID, CATEGORY
ORDER BY AB.AUTHOR_ID, CATEGORY DESC;

-- oracle
SELECT AB.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
FROM (SELECT *
    FROM BOOK NATURAL JOIN BOOK_SALES
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01') AB 
    INNER JOIN AUTHOR C
ON AB.AUTHOR_ID = C.AUTHOR_ID
GROUP BY AB.AUTHOR_ID, CATEGORY, AUTHOR_NAME
ORDER BY AB.AUTHOR_ID, CATEGORY DESC;