-- https://school.programmers.co.kr/learn/courses/30/lessons/59413#qna

-- mysql
WITH RECURSIVE NUMBER AS (
    SELECT 0 HOUR
    UNION ALL
    SELECT HOUR+1 FROM NUMBER WHERE HOUR < 23
)

SELECT A.HOUR, 
       CASE WHEN COUNT IS NULL THEN 0 ELSE COUNT END AS COUNT
FROM NUMBER A LEFT JOIN (
    SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) B
ON A.HOUR = B.HOUR;

-- oracle
SELECT A.HOUR, 
       CASE WHEN B.COUNT IS NULL THEN 0 ELSE B.COUNT END COUNT
FROM (SELECT LEVEL - 1 HOUR FROM DUAL CONNECT BY LEVEL - 1 < 24) A LEFT JOIN (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
) B
ON A.HOUR = B.HOUR
ORDER BY A.HOUR;