-- https://school.programmers.co.kr/learn/courses/30/lessons/164668

-- mysql
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER GU JOIN 
     (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD WHERE STATUS = 'DONE' GROUP BY WRITER_ID) GB
ON GU.USER_ID = GB.WRITER_ID
WHERE TOTAL_SALES >= 700000
GROUP BY USER_ID
ORDER BY TOTAL_SALES;

-- oracle
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER GU JOIN 
     (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD WHERE STATUS = 'DONE' GROUP BY WRITER_ID) GB
ON GU.USER_ID = GB.WRITER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;