-- https://school.programmers.co.kr/learn/courses/30/lessons/151139

-- mysql
SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
) AND DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC;

-- oracle
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYY') = '2022' AND
          (TO_NUMBER(TO_CHAR(START_DATE, 'MM')) BETWEEN 8 AND 10)
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
) AND TO_CHAR(START_DATE, 'YYYY') = '2022' AND (TO_NUMBER(TO_CHAR(START_DATE, 'MM')) BETWEEN 8 AND 10)
GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), CAR_ID DESC;