-- https://school.programmers.co.kr/learn/courses/30/lessons/133026

-- mysql
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER)
FROM FIRST_HALF FHF INNER JOIN ICECREAM_INFO IFO
ON FHF.FLAVOR = IFO.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;

-- oracle
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF FHF INNER JOIN ICECREAM_INFO IFO
ON FHF.FLAVOR = IFO.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;