-- https://school.programmers.co.kr/learn/courses/30/lessons/131532#qna

-- mysql
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT USER_ID) USERS
FROM USER_INFO NATURAL JOIN ONLINE_SALE
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;

-- oracle
SELECT TO_NUMBER(TO_CHAR(SALES_DATE, 'YYYY')) YEAR, TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH, GENDER, COUNT(DISTINCT USER_ID) USERS
FROM USER_INFO NATURAL JOIN ONLINE_SALE
WHERE GENDER IS NOT NULL
GROUP BY TO_NUMBER(TO_CHAR(SALES_DATE, 'YYYY')), TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')), GENDER
ORDER BY TO_NUMBER(TO_CHAR(SALES_DATE, 'YYYY')), TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')), GENDER;