-- https://school.programmers.co.kr/learn/courses/30/lessons/59415

-- mysql
SELECT DATETIME
FROM ANIMAL_INS
ORDER BY DATETIME DESC
LIMIT 1;

-- oracle
SELECT DATETIME
FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME DESC)
WHERE ROWNUM = 1;