-- https://school.programmers.co.kr/learn/courses/30/lessons/131697

-- mysql
SELECT PRICE MAX_PRICE
FROM PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCT);

-- oracle
SELECT PRICE MAX_PRICE
FROM PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCT);